### ISSUE TITLE
16页的2.1依赖注入章节的维基百科的翻译需要调整

### ISSUE THREAD

**Issue by jxzly229190** [ABPFrameWorkGroup/AbpDocument2Chinese#1]
章节：2.1 ABP依赖注入
页码：16
位置：维基百科说：“依赖注入 是一种软件设计模式的......

![default](https://cloud.githubusercontent.com/assets/3610845/8228617/ebfe75a2-15e2-11e5-877d-433f1bc895b7.jpg)

**Comment by tiandao-dongguan** [comment]
已经收到~

------------------ 原始邮件 ------------------
发件人: "Jimmyzhang";notifications@github.com;
发送时间: 2015年6月18日(星期四) 下午5:53
收件人: "ABPFrameWorkGroup/AbpDocument2Chinese"AbpDocument2Chinese@noreply.github.com; 

主题: [AbpDocument2Chinese] 16页的2.1依赖注入章节的维基百科的翻译需要调整 (#1)

ok~已经收到~

章节：2.1 ABP依赖注入
 页码：16
 位置：维基百科说：“依赖注入 是一种软件设计模式的......

**Comment by jxzly229190** [comment]
@tiandao-dongguan 只是报Issue（_会有邮件提醒_），做下记录，便于跟踪问题。你不用记录，也不着急解决，有时间再看。**如果你发现问题请创建Issue，也倡导大家到这里来报问题**，一起改进 :smile: 

### 报Issue步骤：

![issue1](https://cloud.githubusercontent.com/assets/3610845/8247666/9c4d05dc-1687-11e5-9a63-ee25041b2699.jpg)
![issue2](https://cloud.githubusercontent.com/assets/3610845/8247667/9c4f9d9c-1687-11e5-83ee-b427c015e5f1.jpg)
![issue3](https://cloud.githubusercontent.com/assets/3610845/8247668/9c51367a-1687-11e5-886e-e640b2d3e85e.jpg)

**Comment by tiandao-dongguan** [comment]
明白了，你还是很负责任的人啊。

**Comment by AlexGeller** [comment]
以下是我翻译的。

依赖注入是一种软件设计模式，指一个或多个依赖（或服务）被注入，或通过引用传递，传入一个依赖对象（或客户端）并成为客户状态的一部分。模式通过自身的行为分离了客户依赖的创建，这允许程序设计是松耦合的，同时遵循依赖倒置和单一职责原则。与服务定位器模式直接进行对比，它允许客户了解他们用来查找依赖的机制。

**Comment by AlexGeller** [comment]
以下是我翻译的。

依赖注入是一种软件设计模式，指一个或多个依赖（或服务）被注入，或通过引用传递，传入一个依赖对象（或客户端）并成为客户状态的一部分。模式通过自身的行为分离了客户依赖的创建，这允许程序设计是松耦合的，同时遵循依赖倒置和单一职责原则。与服务定位器模式直接进行对比，它允许客户了解他们用来查找依赖的机制。

**Comment by AlexGeller** [comment]
以下是我翻译的。

依赖注入是一种软件设计模式，指一个或多个依赖（或服务）被注入，或通过引用传递，传入一个依赖对象（或客户端）并成为客户状态的一部分。模式通过自身的行为分离了客户依赖的创建，这允许程序设计是松耦合的，同时遵循依赖倒置和单一职责原则。与服务定位器模式直接进行对比，它允许客户了解他们用来查找依赖的机制。

**Comment by AlexGeller** [comment]
以下是我翻译的。

依赖注入是一种软件设计模式，指一个或多个依赖（或服务）被注入，或通过引用传递，传入一个依赖对象（或客户端）并成为客户状态的一部分。模式通过自身的行为分离了客户依赖的创建，这允许程序设计是松耦合的，同时遵循依赖倒置和单一职责原则。与服务定位器模式直接进行对比，它允许客户了解他们用来查找依赖的机制。

**Comment by tiandao-dongguan** [comment]
采用你的翻译，感谢支持。
