### ISSUE TITLE
这个还有在维护么？

### ISSUE THREAD

**Issue by xyfy** [ABPFrameWorkGroup/AbpDocument2Chinese#100]
感觉好久没有更新发布版本了

**Comment by jxzly229190** [comment]
在的，虽然不是那么活跃(^_^)v

发自我的 iPhone

在 2018年4月18日，上午9:17，xyfy <notifications@github.com<mailto:notifications@github.com>> 写道：


感觉好久没有更新发布版本了

**Comment by daconglee** [comment]
怎么不更新

**Comment by xyfy** [comment]
....感觉不像在维护的状态。。。。代码很久没有更新了
