### ISSUE TITLE
请问如何基于abp实现动态加载模块的功能

### ISSUE THREAD

**Issue by lun3322** [ABPFrameWorkGroup/AbpDocument2Chinese#34]
就像Orchard或者nop的动态模块系统

**Comment by tiandao-dongguan** [comment]
abp的模块是区别于Orchard或者nop的动态模块系统的，比如nop的插件，可以独立于现有系统，通过配置文件来标识，或者可以很方便的通过修改自带的插件来实现，nop的插件可以独立，只需要关键的插件dll即可，任何人，任何系统注册后都可以调用。

abp的模块目前还没实现完全独立，因为abp的模块或者说程序集之间有引用关系，他并不能动态的加载。

**Comment by dusdong** [comment]
我感觉abp的模块主要是为了程序开发层面组织代码的便利性吧

**Comment by tiandao-dongguan** [comment]
可以这么认为，abp模块主要是功能的封装，比如权限模块，博客模块，都是需要多个程序集(DLL).也可以是单个程序集，比如webapi模块。

**Comment by lun3322** [comment]
在企业应用中,一个主项目,下面有博客,cms,oa三个项目,怎么组织项目呢,基于abp
要求是部署在同一个IIS站点下面,不可以使用 添加应用程序 的方式.

**Comment by lun3322** [comment]
作者说在1.0版本会增加这个功能
