### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by csharpweb** [ABPFrameWorkGroup/AbpDocument2Chinese#36]
首先，感谢各位大神的无私奉献！！！！
我在这里提一个很小很小的建议：那就是一些专业的英文名词建议还是保留的好啊，翻译过来看着反而更迷糊。
比如说：（工人）worker、（经理）manager等等。
看着好别扭。。。而且又不易懂了。。

**Comment by carldai0106** [comment]
@csharpweb 
对翻译不当的地方，您可以提交PR。我们会合并。
