### ISSUE TITLE
官网又更新了几篇。

### ISSUE THREAD

**Issue by aricyu** [ABPFrameWorkGroup/AbpDocument2Chinese#37]
首先，感谢各位大神的无私奉献！！！！
本人非常想做出贡献，奈何英文水平太烂，离开了翻译软件基本就看不懂英文了。

abp官网最近又更新了几篇文档，不知各位大神能否百忙中抽点时间跟进一下？
非常非常感谢各位大神的无私奉献！！！！

**Comment by carldai0106** [comment]
有时间我会翻译一下，关于时区那篇，作者本人都没写好文档，根本看不出怎么弄。

**Comment by carldai0106** [comment]
已经翻译
