### ISSUE TITLE
你好，我想撩一下你。可以吗?

### ISSUE THREAD

**Issue by ltm0203** [ABPFrameWorkGroup/AbpDocument2Chinese#85]
你好，我是角落的白板笔，想撩一下你。
我想认识下你，因为你一直在更新abp的中文文档。可以加一个，您的QQ或者微信号码吗?
我的QQ号：623037939
也邀请您加入我们的群：134710707 ABP架构设计交流群

果然是全球最大的同性交友网站。

**Comment by carldai0106** [comment]
@ltm0203 
一直在你群里，有一天被你踢出了群，可能是很少发言，只是静静的看着。
我的马甲是： 深圳-carl，QQ：280141563

**Comment by tiandao-dongguan** [comment]
不会吧，老兄，我没踢你啊~




------------------ 原始邮件 ------------------
发件人: "carldai0106";<notifications@github.com>;
发送时间: 2017年7月10日(星期一) 下午5:16
收件人: "ABPFrameWorkGroup/AbpDocument2Chinese"<AbpDocument2Chinese@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [ABPFrameWorkGroup/AbpDocument2Chinese] 你好，我想撩一下你。可以吗? (#85)




@ltm0203
 一直在你群里，有一天被你踢出了群，可能是很少发言，只是静静的看着。
 我的马甲是： 深圳-carl，QQ：280141563

**Comment by carldai0106** [comment]
@tiandao-dongguan 我不是说你啊。

**Comment by ltm0203** [comment]
我的错。已经加你好友了。
