### ISSUE TITLE
拼写错误

### ISSUE THREAD

**Issue by tangdf** [ABPFrameWorkGroup/AbpDocument2Chinese#88]
<https://github.com/ABPFrameWorkGroup/AbpDocument2Chinese/blob/master/Markdown/Abp/1.3ABP%E6%80%BB%E4%BD%93%E4%BB%8B%E7%BB%8D-%E6%A8%A1%E5%9D%97%E7%B3%BB%E7%BB%9F.md#135-插件模块>

**PlugInFolderSource** 类实现了该接口，它可以被用来加载指定文件夹下的程序集。

名字写错了，应该是**FolderPlugInSource**。

**Comment by carldai0106** [comment]
其实是官方文档错了，谢谢指出，已经改好了。
