### ISSUE TITLE
PDF文档第8页一处小typo

### ISSUE THREAD

**Issue by user3301** [ABPFrameWorkGroup/AbpDocument2Chinese#92]
文档第八页中引用的代码案例为"MyBlogApplicationModule"类，文中写为"MybolgApplication"，小typo无伤大雅。

**Comment by nicoxiang** [comment]
@user3301 原文为其实是Blog module，翻译成MybolgApplication模块也符合意思，并不一定要对应具体类名，Markdown中也修复了

**Comment by user3301** [comment]
我只是想指出“blog” ->"bolg"这个小typo，表达不准确尽请谅解

**Comment by nicoxiang** [comment]
@user3301 恩恩，Pdf很多都是旧的，Markdown比较新

**Comment by jxzly229190** [comment]
Pdf是否可以不需要了，或者说readme说明下pdf版本较旧以免误导

发自我的 iPhone

在 2018年1月27日，上午8:56，Nico.R.Xiang <notifications@github.com<mailto:notifications@github.com>> 写道：


@user3301<https://github.com/user3301> 恩恩，Pdf很多都是旧的，Markdown比较新

**Comment by nicoxiang** [comment]
@carldai0106 是否可以考虑删除，或者是否有直接mardowntopdf的工具，且需要另外维护Pdf及Word成本较高

**Comment by carldai0106** [comment]
汗，这个要找天道！我没权限删除。
